[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc = "0.8.24"

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true